name: Prueba de Integración Continua

on:
  push:
    branches:
      - main
env:
  NAME_USER: prueba 002
  
jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Ejecutar Script de Prueba
        run: |
          echo "¡Hola, esto es una prueba!"
